### PR TITLE
add RequestHandler and ModelController fixed #32

### LINKED ISSUE #32: create abstract AJAX-RequestHandler
- receive the request
- instantiate the model-class (filtered by given action-parameter!?)
- start the jobs for db-api
- response

### PR DESCRIPTION
**Pull request by WilsonMonkey**
todo_controller.js: change action-attribute in parameters-array for ajax-request

### CODE REVIEW

**Comment by ghost** [comment]
Why do you create a variable named $request inside the ModelController if you never use it, but $_REQUEST?
Also I won't use a saveNewTicket() method but create a method that can save every ticket (new or just updated) and I would place it inside another class, not the one representing our model itself.

**Comment by WilsonMonkey** [comment]
I will fix the issue with the unused $request-param as quickly as possible.
Why you wouldn't add the saveNewTicket()-function in the db-modelclass from the affected table? I think there have to be the db-functions for its table. Where would you add functions like this?
For Updating I would create a updateTicket()-function to the modelclass.  Save and Update should be different things in different function or what you think?

Hint: You can create comments directly in the comitted code next to each line. Very nice features ;-)

**Comment by ghost** [comment]
In my eyes the modelclass shouldn't contain any business logic. I would create an DAO (Data Access Object) that is as abstract as possible. I don't know if its possible whith ActivRecords, but this DAO would have functions like
- create(), update(), delete()
- getByID(), getByProperty()

that are needed for all tables. If there are, for example, some methods we only need for the Tickets, i would extend from this DAO and add the new methods to the TicketDAO class.

**Comment by WilsonMonkey** [comment]
These functions are already implemented in the ActiveRecord library. We need only some classes to call them. 

The convention of ActiveRecord requires a model-dir where to put the modelclasses which extends ActiveRecord/Model. 
http://www.phpactiverecord.org/projects/main/wiki/Quick_Start
http://www.phpactiverecord.org/projects/main/wiki/Conventions

If we want to move to another ORM, we have to discuss it more in detail at the weekend.

**Comment by WilsonMonkey** [comment]
issue with unused variable fixed in 82ec1103ee7e1c3f61c17e7cc973638c5a80f8df

**Comment by WilsonMonkey** [comment]
I have some major problems to check out this branch in phpstorm, because of the name starts with a hyphen. In the future we should never create branches which names starts with hyphens.

**Pull request closed without merging**
